# Server configuration
server.port=${PORT:8080}
spring.application.name=xebia-lms-merged-backend

# Multipart configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Database Configuration (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/learning_platform}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Jitendra@7}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari Connection Pool configuration
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=15000

# JPA / Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL Init configuration
spring.sql.init.mode=never

# Redis configuration
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
spring.data.redis.host=${SPRING_REDIS_HOST:${REDIS_HOST:localhost}}
spring.data.redis.port=${SPRING_REDIS_PORT:${REDIS_PORT:6379}}
spring.data.redis.password=${SPRING_REDIS_PASSWORD:${REDIS_PASSWORD:}}
spring.data.redis.timeout=60000
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED:false}

# JWT security parameters
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# Cloudinary parameters (filled by environment variables at runtime)
# For AMS:
app.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dnplvm1es}
app.cloudinary.api-key=${CLOUDINARY_API_KEY:658889419438443}
app.cloudinary.api-secret=${CLOUDINARY_API_SECRET:b1YxF7d9kO3UI6rSXDqGXJHNGn8}

# For LMS:
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dnplvm1es}
cloudinary.api-key=${CLOUDINARY_API_KEY:658889419438443}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:b1YxF7d9kO3UI6rSXDqGXJHNGn8}
